### ISSUE TITLE
how to use functions feature within continuous conversation

### ISSUE THREAD

**Issue by For-December** [Maxuss/chatgpt_rs#70]
Thank you for developing this powerful lib!
It always works well, but when I try to use functions feature, I' m in trouble.
I want to fulfill a continuous conversation with functions feature, for instance: 
- ask chatGPT what' s the time
- chatGPT call my function to get current time
- then chatGPT reply to me with the time that my function returns

Just like the example: https://openai.com/blog/function-calling-and-other-api-updates
![image](https://github.com/Maxuss/chatgpt_rs/assets/100057209/8e0861d1-3f94-4935-b55e-a63816f60003)

Here is my test code:
```rust
  // build conversation and send to openAI
  conversation.add_function(get_current_time()).unwrap();
  let res = conversation
      .send_message_functions(ask)  // ask is "what' s the time now?"
      .await
      .unwrap()
      .message_choices;
```
about get_current_time:
```rust
/// get current time
///
/// * time - the time that user asks
#[gpt_function]
async fn get_current_time(time: String) -> Value {
    println!("AI uses param: {time}");
    return Ok(json!({
        "time":"10:30"
    }));
}
```
my function ( get_current_time ) was called successfully, but I could' t get a expected reply about current time.

message_functions' length is 1, content is empty str
called message().content also return empty str

history like this: 
![image](https://github.com/Maxuss/chatgpt_rs/assets/100057209/9f810c34-f83d-46a2-8b54-382682a8b72b)

maybe need this?( I guess...)
![image](https://github.com/Maxuss/chatgpt_rs/assets/100057209/73466989-b0de-4076-bbb6-8d1fa312d42c)
and when I called `send_message_functions` again, error occur:
![image](https://github.com/Maxuss/chatgpt_rs/assets/100057209/5c260413-3567-435b-b568-1abc994180b6)
 

I tried again and again, but couldn't be able to solve it, hope to get help

**Comment by For-December** [comment]
and    src\api\chatgpt:95: 14 is here
![image](https://github.com/Maxuss/chatgpt_rs/assets/100057209/153f058c-88f3-424a-aa16-5777ccff8c7e)

**Comment by Maxuss** [comment]
Could you check if the issue still persists with version from the [function-invocation-fix](https://github.com/Maxuss/chatgpt_rs/tree/function-invocation-fix) branch?

**Comment by For-December** [comment]
I write a testing code just now,  the issue still persists.
But I got a warning while running, do I use `functions feature` correctly?
Here are all about testing code:
- main logic
```rust
  // some config code for client......

   let mut conversation = client.new_conversation();
    conversation.add_function(get_current_time()).unwrap();

    let res = conversation
        .send_message_functions("Please tell the current time.")
        .await
        .unwrap()
        .message_choices;

    println!("{}", res.len());
    for ele in res {
        println!("ele is: {}", ele.message.content);
    }
    println!("\nhistory is:{:#?}", conversation.history);
```
- gpt_function
```rust
/// get current time
///
/// * time - the time that user asks
#[gpt_function]
async fn get_current_time(time: String) -> Result<Value> {
    println!("AI uses param: {time}");
    let result: serde_json::Value = serde_json::json!({
        "time":"10:30"
    });
    result
}
```

- Cargo.toml
```toml
[package]
name = "test_gpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chatgpt_rs = { git = "https://github.com/Maxuss/chatgpt_rs", features = [
    "functions",
], branch = "function-invocation-fix" }
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde = { version = "1.0", features = ["derive"] }
```
- All output
![image](https://github.com/Maxuss/chatgpt_rs/assets/100057209/5bf01470-241e-4d01-ab56-8166564957f8)
